name: Deploy to Google Cloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: $ {{ secrets.GOOGLE_PROJECT }}
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/$GOOGLE_PROJECT/mission-5/
  GKE_CLUSTER: mission-5-cluster
  GKE_ZONE: us-central1-c
  IMAGE_NAME: mission5-backend
  TAG: latest
  
jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
    
  # This workflow contains a two jobs, one called "build_test" and a second called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Steps represent a sequence of tasks that will be executed as part of the job
      - name: code checkout
        uses: actions/checkout@v4

      - id: "auth"
        uses: google-github-actions/auth@v1
        with:
            credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with: 
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          export_default_credentials: true

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          cd backend 
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/mission-5/mission5-backend:latest .

      - name: Push Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/mission-5/mission5-backend:latest

      - name: Deploy to GKE
        run: |-
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.REGION }}
       


